"""empty message

Revision ID: 3574bab9b15
Revises: 8a85c89294e
Create Date: 2014-03-13 13:25:27.309467

"""

# revision identifiers, used by Alembic.
revision = '3574bab9b15'
down_revision = '8a85c89294e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.drop_column('post', 'user_id')
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), server_default="nextval('author_id_seq'::regclass)", nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'author_pkey')
    )
    op.drop_table('user')
    ### end Alembic commands ###
