"""empty message

Revision ID: 3db0ba286df4
Revises: 56c120a684e1
Create Date: 2014-03-13 17:48:25.314282

"""

# revision identifiers, used by Alembic.
revision = '3db0ba286df4'
down_revision = '56c120a684e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
