"""empty message

Revision ID: 464bc5e325cc
Revises: 12628e2efa0b
Create Date: 2014-03-12 19:23:48.999099

"""

# revision identifiers, used by Alembic.
revision = '464bc5e325cc'
down_revision = '12628e2efa0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
